const INDIA_DATA = [
  // NOTE:
  // This dataset is intentionally expressed as: { state_name, state_code, districts:[...] }
  // The seeder script dynamically detects actual column names and then tries multiple
  // district_master insertion strategies (state_id/state_code/state/stateId).
  // Therefore the dataset focuses on correct *values* (state_code + district_name).
  //
  // If you later want “exact 802” matching with a specific district-creation cut-off year,
  // replace district lists with that authoritative dataset.

  // -------------------- 29 States + 8 UTs (via provided codes) --------------------
  {
    state_name: "Andhra Pradesh",
    state_code: "AP",
    districts: [
      "Anantapur",
      "Chittoor",
      "East Godavari",
      "Guntur",
      "Kadapa",
      "Krishna",
      "Kurnool",
      "Nellore",
      "Prakasam",
      "Srikakulam",
      "Visakhapatnam",
      "Vizianagaram",
      "West Godavari",
      "YSR Kadapa",
    ],
  },
  {
    state_name: "Arunachal Pradesh",
    state_code: "AR",
    districts: [
      "Anjaw",
      "Changlang",
      "Dibang Valley",
      "East Kameng",
      "East Siang",
      "Itanagar",
      "Lohit",
      "Lower Dibang Valley",
      "Lower Siang",
      "Lower Subansiri",
      "Papum Pare",
      "Tawang",
      "Tirap",
      "Upper Siang",
      "Upper Subansiri",
      "West Kameng",
      "West Siang",
    ],
  },
  {
    state_name: "Assam",
    state_code: "AS",
    districts: [
      "Baksa",
      "Barpeta",
      "Bongaigaon",
      "Cachar",
      "Charaideo",
      "Chirang",
      "Darrang",
      "Dhemaji",
      "Dhubri",
      "Dibrugarh",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Hojai",
      "Jorhat",
      "Kamrup",
      "Kamrup Metropolitan",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Majuli",
      "Morigaon",
      "Nagaon",
      "Nalbari",
      "Sivasagar",
      "Sonitpur",
      "South Salmara-Mankachar",
      "Tinsukia",
      "Udalguri",
      "West Karbi Anglong",
      "Dibrugarh",
    ],
  },
  {
    state_name: "Bihar",
    state_code: "BR",
    districts: [
      "Araria",
      "Arwal",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran",
    ],
  },
  {
    state_name: "Chhattisgarh",
    state_code: "CT",
    districts: [
      "Balod",
      "Baloda Bazar",
      "Balrampur",
      "Bastar",
      "Bemetara",
      "Bijapur",
      "Bilaspur",
      "Dantewada",
      "Dhamtari",
      "Durg",
      "Gariaband",
      "Janjgir-Champa",
      "Jashpur",
      "Kabirdham",
      "Kanker",
      "Kondagaon",
      "Korba",
      "Korea",
      "Mahasamund",
      "Manendragarh-Chirmiri-Bharatpur",
      "Mohla-Manpur",
      "Mungeli",
      "Narayanpur",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Sakti",
      "Sarangarh-Bilaigarh",
      "Sukma",
      "Surajpur",
      "Surguja",
    ],
  },
  {
    state_name: "Goa",
    state_code: "GA",
    districts: ["North Goa", "South Goa"],
  },
  {
    state_name: "Gujarat",
    state_code: "GJ",
    districts: [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Aravalli",
      "Banaskantha",
      "Bharuch",
      "Bhavnagar",
      "Botad",
      "Chhota Udaipur",
      "Dahod",
      "Dang",
      "Devbhoomi Dwarka",
      "Gandhinagar",
      "Gir Somnath",
      "Jamnagar",
      "Kheda",
      "Kutch",
      "Mahisagar",
      "Mehsana",
      "Morbi",
      "Narmada",
      "Navsari",
      "Panchmahal",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Sabarkantha",
      "Surat",
      "Surendranagar",
      "Tapi",
      "Vadodara",
      "Valsad",
    ],
  },
  {
    state_name: "Haryana",
    state_code: "HR",
    districts: [
      "Ambala",
      "Bhiwani",
      "Charkhi Dadri",
      "Faridabad",
      "Fatehabad",
      "Gurugram",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Nuh",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamunanagar",
    ],
  },
  {
    state_name: "Himachal Pradesh",
    state_code: "HP",
    districts: [
      "Bilaspur",
      "Chamba",
      "Hamirpur",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahaul and Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur",
      "Solan",
      "Una",
    ],
  },
  {
    state_name: "Jharkhand",
    state_code: "JH",
    districts: [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribagh",
      "Jamtara",
      "Khunti",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamu",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Saraikela-Kharsawan",
      "Simdega",
      "West Singhbhum",
    ],
  },
  {
    state_name: "Karnataka",
    state_code: "KA",
    districts: [
      "Bagalkote",
      "Bangalore Rural",
      "Bangalore Urban",
      "Belagavi",
      "Ballari",
      "Bidar",
      "Chamarajanagar",
      "Chikkaballapur",
      "Chikkamagaluru",
      "Chitradurga",
      "Dakshina Kannada",
      "Davangere",
      "Dharwad",
      "Gadag",
      "Gulbarga",
      "Hassan",
      "Haveri",
      "Kalaburagi",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysuru",
      "Raichur",
      "Ramanagara",
      "Shivamogga",
      "Tumakuru",
      "Udupi",
      "Vijayapura",
      "Yadgir",
    ],
  },
  {
    state_name: "Kerala",
    state_code: "KL",
    districts: [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thiruvananthapuram",
      "Thrissur",
      "Wayanad",
    ],
  },
  {
    state_name: "Madhya Pradesh",
    state_code: "MP",
    districts: [
      "Agar",
      "Alirajpur",
      "Anuppur",
      "Ashok Nagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Deoghar",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa",
      "Khargone",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Panna",
      "Raisen",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
      "West Nimar",
      "East Nimar",
    ],
  },
  {
    state_name: "Maharashtra",
    state_code: "MH",
    districts: [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Beed",
      "Bhandara",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai City",
      "Mumbai Suburban",
      "Nagpur",
      "Nanded",
      "Nandurbar",
      "Nashik",
      "Osmanabad",
      "Palghar",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sangli",
      "Satara",
      "Sindhudurg",
      "Solapur",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
  },
  {
    state_name: "Manipur",
    state_code: "MN",
    districts: ["Bishnupur", "Chandel", "Imphal East", "Imphal West", "Jiribam", "Kakching", "Noney", "Pherzawl", "Senapati", "Tamenglong", "Thoubal", "Ukhrul"],
  },
  {
    state_name: "Meghalaya",
    state_code: "ML",
    districts: [
      "East Garo Hills",
      "East Jaintia Hills",
      "East Khasi Hills",
      "North Garo Hills",
      "Ri-Bhoi",
      "South Garo Hills",
      "South Jaintia Hills",
      "South West Garo Hills",
      "South West Khasi Hills",
      "West Garo Hills",
      "West Jaintia Hills",
      "West Khasi Hills",
    ],
  },
  {
    state_name: "Mizoram",
    state_code: "MZ",
    districts: ["Aizawl", "Champhai", "Khawzawl", "Kolasib", "Lunglei", "Lwthang", "Mamit", "Saiha", "Saitual", "Serchhip"],
  },
  {
    state_name: "Nagaland",
    state_code: "NL",
    districts: ["Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Niuland", "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto"],
  },
  {
    state_name: "Odisha",
    state_code: "OD",
    districts: [
      "Angul",
      "Balangir",
      "Balasore",
      "Bargarh",
      "Bhadrak",
      "Boudh",
      "Cuttack",
      "Deogarh",
      "Dhenkanal",
      "Gajapati",
      "Ganjam",
      "Jagatsinghpur",
      "Jajpur",
      "Jharsuguda",
      "Kalahandi",
      "Kandhamal",
      "Kendrapara",
      "Khurda",
      "Koraput",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangapur",
      "Nayagarh",
      "Nuapada",
      "Puri",
      "Rayagada",
      "Sambalpur",
      "Subarnapur",
      "Sundargarh",
    ],
  },
  {
    state_name: "Punjab",
    state_code: "PB",
    districts: [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Ferozepur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Malerkotla",
      "Mansa",
      "Moga",
      "Muktsar",
      "Pathankot",
      "Patiala",
      "Rupnagar",
      "Sangrur",
      "SAS Nagar",
      "Tarn Taran",
    ],
  },
  {
    state_name: "Rajasthan",
    state_code: "RJ",
    districts: [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Baran",
      "Barmer",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Dungarpur",
      "Hanumangarh",
      "Jaipur",
      "Jaisalmer",
      "Jalore",
      "Jhalawar",
      "Jhunjhunu",
      "Jodhpur",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Pratapgarh",
      "Rajsamand",
      "Sawai Madhopur",
      "Sikar",
      "Sirohi",
      "Tonk",
      "Udaipur",
    ],
  },
  {
    state_name: "Sikkim",
    state_code: "SK",
    districts: ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  },
  {
    state_name: "Tamil Nadu",
    state_code: "TN",
    districts: [
      "Ariyalur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kallakurichi",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Madurai",
      "Mayiladuthurai",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Tenkasi",
      "Thanjavur",
      "Theni",
      "Thiruvallur",
      "Thiruvarur",
      "Thoothukudi",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tirupathur",
      "Tiruppur",
      "Vellore",
      "Viluppuram",
      "Virudhunagar",
    ],
  },
  {
    state_name: "Telangana",
    state_code: "TG",
    districts: [
      "Adilabad",
      "Bhadradri Kothagudem",
      "Hyderabad",
      "Jagtial",
      "Jangaon",
      "Jayashankar Bhupalpally",
      "Jogulamba Gadwal",
      "Kamareddy",
      "Karimnagar",
      "Khammam",
      "Komaram Bheem Asifabad",
      "Mahabubabad",
      "Mahbubnagar",
      "Mancherial",
      "Medak",
      "Medchal–Malkajgiri",
      "Mulugu",
      "Nagarkurnool",
      "Nalgonda",
      "Narayanpet",
      "Nirmal",
      "Nizamabad",
      "Peddapalli",
      "Rajanna Sircilla",
      "Ranga Reddy",
      "Sangareddy",
      "Siddipet",
      "Suryapet",
      "Vikarabad",
      "Wanaparthy",
      "Warangal",
      "Yadadri Bhuvanagiri",
    ],
  },
  {
    state_name: "Tripura",
    state_code: "TR",
    districts: ["Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"],
  },
  {
    state_name: "Uttar Pradesh",
    state_code: "UP",
    districts: [
      "Agra",
      "Aligarh",
      "Allahabad",
      "Ambedkar Nagar",
      "Amethi",
      "Amroha",
      "Auraiya",
      "Azamgarh",
      "Bagpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Faizabad",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kasganj",
      "Kaushambi",
      "Kushinagar",
      "Lakhimpur Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "Rae Bareli",
      "Rampur",
      "Saharanpur",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamli",
      "Shravasti",
      "Siddharthnagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
  },
  {
    state_name: "Uttarakhand",
    state_code: "UT",
    districts: ["Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"],
  },
  {
    state_name: "West Bengal",
    state_code: "WB",
    districts: [
      "Alipurduar",
      "Bankura",
      "Birbhum",
      "Cooch Behar",
      "Dakshin Dinajpur",
      "Darjeeling",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Jhargram",
      "Kalimpong",
      "Kolkata",
      "Malda",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "Paschim Bardhaman",
      "Purba Bardhaman",
      "Purba Medinipur",
      "Puruliya",
      "South 24 Parganas",
      "Uttar Dinajpur",
    ],
  },

  // -------------------- Union Territories --------------------
  {
    state_name: "Andaman and Nicobar Islands",
    state_code: "AN",
    districts: ["Nicobar", "North and Middle Andaman", "South Andaman"],
  },
  {
    state_name: "Chandigarh",
    state_code: "CH",
    districts: ["Chandigarh"],
  },
  {
    state_name: "Dadra and Nagar Haveli and Daman and Diu",
    state_code: "DN",
    districts: ["Dadra and Nagar Haveli", "Daman", "Diu"],
  },
  {
    state_name: "Jammu and Kashmir",
    state_code: "JK",
    districts: ["Anantnag", "Bandipora", "Baramulla", "Budgam", "Doda", "Ganderbal", "Jammu", "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Leh and Ladakh", "Poonch", "Pulwama", "Rajouri", "Ramban", "Reasi", "Samba", "Shopian", "Srinagar", "Udhampur"],
  },
  {
    state_name: "Ladakh",
    state_code: "LA",
    districts: ["Kargil", "Leh"],
  },
  {
    state_name: "Lakshadweep",
    state_code: "LD",
    districts: ["Lakshadweep"],
  },
  {
    state_name: "Delhi",
    state_code: "DL",
    districts: ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", "North West Delhi", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"],
  },
  {
    state_name: "Puducherry",
    state_code: "PY",
    districts: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
  },
];


function toCode(text) {
  return String(text || "")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

async function upsertGenericMaster(client, table, { code, name, parentCode }) {
  const normalizedCode = toCode(code);
  if (!normalizedCode) return;
  await client.query(
    `INSERT INTO ${table} (id, code, name, parent_code, active, created_at, updated_at)
     VALUES ($1, $2, $3, $4, TRUE, NOW(), NOW())
     ON CONFLICT (code) DO UPDATE SET
       name = EXCLUDED.name,
       parent_code = EXCLUDED.parent_code,
       active = TRUE,
       updated_at = NOW()`,
    [`${table}_${normalizedCode}`, normalizedCode, name || normalizedCode, parentCode || null]
  );
}

// Real schema (see server/utils/masterCatalogMigration.js `ensureGenericMasterTable`) is
// id/code/name/parent_code/active — not the state_id/state_code/state/stateId columns this
// seeder used to guess at. Upsert directly against that schema instead of bruteforcing columns.
export async function runSeeder(poolInstance) {
  const client = await poolInstance.connect();
  try {
    console.log("[Seeder] Seeding state_master / district_master...");

    for (const item of INDIA_DATA) {
      const stateCode = item.state_code.toUpperCase();
      await upsertGenericMaster(client, "state_master", { code: stateCode, name: item.state_name });

      for (const distName of item.districts) {
        const districtCode = `${stateCode}_${toCode(distName)}`;
        await upsertGenericMaster(client, "district_master", {
          code: districtCode,
          name: distName,
          parentCode: stateCode,
        });
      }
    }

    console.log("[Seeder] state_master / district_master seeding complete.");
  } catch (error) {
    console.error("[Seeder Error] state/district seeding failed:", error);
  } finally {
    client.release();
  }
}

// -------------------- Indian Railways zones + divisions --------------------
// Best-effort standard list (17 zones). Division codes are generated from the
// division name and are not guaranteed to match official IR codes — review/adjust
// if you have an authoritative reference, since zone/division boundaries do change.
const ZONE_DIVISION_DATA = [
  { zone_code: "CR", zone_name: "Central Railway", divisions: ["Mumbai", "Bhusawal", "Nagpur", "Pune", "Solapur"] },
  { zone_code: "ER", zone_name: "Eastern Railway", divisions: ["Howrah", "Sealdah", "Asansol", "Malda"] },
  { zone_code: "ECR", zone_name: "East Central Railway", divisions: ["Danapur", "Dhanbad", "Pt. Deen Dayal Upadhyaya", "Samastipur", "Sonpur"] },
  { zone_code: "ECOR", zone_name: "East Coast Railway", divisions: ["Khurda Road", "Sambalpur", "Waltair"] },
  { zone_code: "NR", zone_name: "Northern Railway", divisions: ["Delhi", "Ambala", "Ferozpur", "Lucknow", "Moradabad"] },
  { zone_code: "NCR", zone_name: "North Central Railway", divisions: ["Allahabad", "Agra", "Jhansi"] },
  { zone_code: "NER", zone_name: "North Eastern Railway", divisions: ["Izzatnagar", "Lucknow", "Varanasi"] },
  { zone_code: "NFR", zone_name: "Northeast Frontier Railway", divisions: ["Alipurduar", "Katihar", "Lumding", "Rangiya", "Tinsukia"] },
  { zone_code: "NWR", zone_name: "North Western Railway", divisions: ["Jaipur", "Ajmer", "Bikaner", "Jodhpur"] },
  { zone_code: "SR", zone_name: "Southern Railway", divisions: ["Chennai", "Madurai", "Palakkad", "Salem", "Thiruvananthapuram", "Tiruchirapalli"] },
  { zone_code: "SCR", zone_name: "South Central Railway", divisions: ["Secunderabad", "Guntakal", "Guntur", "Hyderabad", "Nanded", "Vijayawada"] },
  { zone_code: "SER", zone_name: "South Eastern Railway", divisions: ["Adra", "Chakradharpur", "Kharagpur", "Ranchi"] },
  { zone_code: "SECR", zone_name: "South East Central Railway", divisions: ["Bilaspur", "Nagpur", "Raipur"] },
  { zone_code: "SWR", zone_name: "South Western Railway", divisions: ["Hubballi", "Bengaluru", "Mysuru"] },
  { zone_code: "WR", zone_name: "Western Railway", divisions: ["Mumbai Central", "Ahmedabad", "Rajkot", "Bhavnagar", "Vadodara", "Ratlam"] },
  { zone_code: "WCR", zone_name: "West Central Railway", divisions: ["Jabalpur", "Bhopal", "Kota"] },
  { zone_code: "KR", zone_name: "Metro Railway Kolkata", divisions: [] },
];

export async function runZoneDivisionSeeder(poolInstance) {
  const client = await poolInstance.connect();
  try {
    console.log("[Seeder] Seeding zone_master / division_master...");

    for (const zone of ZONE_DIVISION_DATA) {
      await upsertGenericMaster(client, "zone_master", { code: zone.zone_code, name: zone.zone_name });

      for (const divisionName of zone.divisions) {
        const divisionCode = `${zone.zone_code}_${toCode(divisionName)}`;
        await upsertGenericMaster(client, "division_master", {
          code: divisionCode,
          name: divisionName,
          parentCode: zone.zone_code,
        });
      }
    }

    console.log("[Seeder] zone_master / division_master seeding complete.");
  } catch (error) {
    console.error("[Seeder Error] zone/division seeding failed:", error);
  } finally {
    client.release();
  }
}