const INDIA_DATA = [
  // NOTE:
  // This dataset is intentionally expressed as: { state_name, state_code, districts:[...] }
  // The seeder script dynamically detects actual column names and then tries multiple
  // district_master insertion strategies (state_id/state_code/state/stateId).
  // Therefore the dataset focuses on correct *values* (state_code + district_name).
  //
  // If you later want “exact 802” matching with a specific district-creation cut-off year,
  // replace district lists with that authoritative dataset.

  // -------------------- 29 States + 8 UTs (via provided codes) --------------------
  {
    state_name: "Andhra Pradesh",
    state_code: "AP",
    districts: [
      "Anantapur",
      "Chittoor",
      "East Godavari",
      "Guntur",
      "Kadapa",
      "Krishna",
      "Kurnool",
      "Nellore",
      "Prakasam",
      "Srikakulam",
      "Visakhapatnam",
      "Vizianagaram",
      "West Godavari",
      "YSR Kadapa",
    ],
  },
  {
    state_name: "Arunachal Pradesh",
    state_code: "AR",
    districts: [
      "Anjaw",
      "Changlang",
      "Dibang Valley",
      "East Kameng",
      "East Siang",
      "Itanagar",
      "Lohit",
      "Lower Dibang Valley",
      "Lower Siang",
      "Lower Subansiri",
      "Papum Pare",
      "Tawang",
      "Tirap",
      "Upper Siang",
      "Upper Subansiri",
      "West Kameng",
      "West Siang",
    ],
  },
  {
    state_name: "Assam",
    state_code: "AS",
    districts: [
      "Baksa",
      "Barpeta",
      "Bongaigaon",
      "Cachar",
      "Charaideo",
      "Chirang",
      "Darrang",
      "Dhemaji",
      "Dhubri",
      "Dibrugarh",
      "Goalpara",
      "Golaghat",
      "Hailakandi",
      "Hojai",
      "Jorhat",
      "Kamrup",
      "Kamrup Metropolitan",
      "Karbi Anglong",
      "Karimganj",
      "Kokrajhar",
      "Lakhimpur",
      "Majuli",
      "Morigaon",
      "Nagaon",
      "Nalbari",
      "Sivasagar",
      "Sonitpur",
      "South Salmara-Mankachar",
      "Tinsukia",
      "Udalguri",
      "West Karbi Anglong",
      "Dibrugarh",
    ],
  },
  {
    state_name: "Bihar",
    state_code: "BR",
    districts: [
      "Araria",
      "Arwal",
      "Aurangabad",
      "Banka",
      "Begusarai",
      "Bhagalpur",
      "Bhojpur",
      "Buxar",
      "Darbhanga",
      "East Champaran",
      "Gaya",
      "Gopalganj",
      "Jamui",
      "Jehanabad",
      "Kaimur",
      "Katihar",
      "Khagaria",
      "Kishanganj",
      "Lakhisarai",
      "Madhepura",
      "Madhubani",
      "Munger",
      "Muzaffarpur",
      "Nalanda",
      "Nawada",
      "Patna",
      "Purnia",
      "Rohtas",
      "Saharsa",
      "Samastipur",
      "Saran",
      "Sheikhpura",
      "Sheohar",
      "Sitamarhi",
      "Siwan",
      "Supaul",
      "Vaishali",
      "West Champaran",
    ],
  },
  {
    state_name: "Chhattisgarh",
    state_code: "CT",
    districts: [
      "Balod",
      "Baloda Bazar",
      "Balrampur",
      "Bastar",
      "Bemetara",
      "Bijapur",
      "Bilaspur",
      "Dantewada",
      "Dhamtari",
      "Durg",
      "Gariaband",
      "Janjgir-Champa",
      "Jashpur",
      "Kabirdham",
      "Kanker",
      "Kondagaon",
      "Korba",
      "Korea",
      "Mahasamund",
      "Manendragarh-Chirmiri-Bharatpur",
      "Mohla-Manpur",
      "Mungeli",
      "Narayanpur",
      "Raigarh",
      "Raipur",
      "Rajnandgaon",
      "Sakti",
      "Sarangarh-Bilaigarh",
      "Sukma",
      "Surajpur",
      "Surguja",
    ],
  },
  {
    state_name: "Goa",
    state_code: "GA",
    districts: ["North Goa", "South Goa"],
  },
  {
    state_name: "Gujarat",
    state_code: "GJ",
    districts: [
      "Ahmedabad",
      "Amreli",
      "Anand",
      "Aravalli",
      "Banaskantha",
      "Bharuch",
      "Bhavnagar",
      "Botad",
      "Chhota Udaipur",
      "Dahod",
      "Dang",
      "Devbhoomi Dwarka",
      "Gandhinagar",
      "Gir Somnath",
      "Jamnagar",
      "Kheda",
      "Kutch",
      "Mahisagar",
      "Mehsana",
      "Morbi",
      "Narmada",
      "Navsari",
      "Panchmahal",
      "Patan",
      "Porbandar",
      "Rajkot",
      "Sabarkantha",
      "Surat",
      "Surendranagar",
      "Tapi",
      "Vadodara",
      "Valsad",
    ],
  },
  {
    state_name: "Haryana",
    state_code: "HR",
    districts: [
      "Ambala",
      "Bhiwani",
      "Charkhi Dadri",
      "Faridabad",
      "Fatehabad",
      "Gurugram",
      "Hisar",
      "Jhajjar",
      "Jind",
      "Kaithal",
      "Karnal",
      "Kurukshetra",
      "Mahendragarh",
      "Nuh",
      "Palwal",
      "Panchkula",
      "Panipat",
      "Rewari",
      "Rohtak",
      "Sirsa",
      "Sonipat",
      "Yamunanagar",
    ],
  },
  {
    state_name: "Himachal Pradesh",
    state_code: "HP",
    districts: [
      "Bilaspur",
      "Chamba",
      "Hamirpur",
      "Kangra",
      "Kinnaur",
      "Kullu",
      "Lahaul and Spiti",
      "Mandi",
      "Shimla",
      "Sirmaur",
      "Solan",
      "Una",
    ],
  },
  {
    state_name: "Jharkhand",
    state_code: "JH",
    districts: [
      "Bokaro",
      "Chatra",
      "Deoghar",
      "Dhanbad",
      "Dumka",
      "East Singhbhum",
      "Garhwa",
      "Giridih",
      "Godda",
      "Gumla",
      "Hazaribagh",
      "Jamtara",
      "Khunti",
      "Koderma",
      "Latehar",
      "Lohardaga",
      "Pakur",
      "Palamu",
      "Ramgarh",
      "Ranchi",
      "Sahibganj",
      "Saraikela-Kharsawan",
      "Simdega",
      "West Singhbhum",
    ],
  },
  {
    state_name: "Karnataka",
    state_code: "KA",
    districts: [
      "Bagalkote",
      "Bangalore Rural",
      "Bangalore Urban",
      "Belagavi",
      "Ballari",
      "Bidar",
      "Chamarajanagar",
      "Chikkaballapur",
      "Chikkamagaluru",
      "Chitradurga",
      "Dakshina Kannada",
      "Davangere",
      "Dharwad",
      "Gadag",
      "Gulbarga",
      "Hassan",
      "Haveri",
      "Kalaburagi",
      "Kodagu",
      "Kolar",
      "Koppal",
      "Mandya",
      "Mysuru",
      "Raichur",
      "Ramanagara",
      "Shivamogga",
      "Tumakuru",
      "Udupi",
      "Vijayapura",
      "Yadgir",
    ],
  },
  {
    state_name: "Kerala",
    state_code: "KL",
    districts: [
      "Alappuzha",
      "Ernakulam",
      "Idukki",
      "Kannur",
      "Kasaragod",
      "Kollam",
      "Kottayam",
      "Kozhikode",
      "Malappuram",
      "Palakkad",
      "Pathanamthitta",
      "Thiruvananthapuram",
      "Thrissur",
      "Wayanad",
    ],
  },
  {
    state_name: "Madhya Pradesh",
    state_code: "MP",
    districts: [
      "Agar",
      "Alirajpur",
      "Anuppur",
      "Ashok Nagar",
      "Balaghat",
      "Barwani",
      "Betul",
      "Bhind",
      "Bhopal",
      "Chhatarpur",
      "Chhindwara",
      "Damoh",
      "Datia",
      "Deoghar",
      "Dewas",
      "Dhar",
      "Dindori",
      "Guna",
      "Gwalior",
      "Harda",
      "Hoshangabad",
      "Indore",
      "Jabalpur",
      "Jhabua",
      "Katni",
      "Khandwa",
      "Khargone",
      "Mandla",
      "Mandsaur",
      "Morena",
      "Narsinghpur",
      "Neemuch",
      "Panna",
      "Raisen",
      "Rajgarh",
      "Ratlam",
      "Rewa",
      "Sagar",
      "Satna",
      "Sehore",
      "Seoni",
      "Shahdol",
      "Shajapur",
      "Sidhi",
      "Singrauli",
      "Tikamgarh",
      "Ujjain",
      "Umaria",
      "Vidisha",
      "West Nimar",
      "East Nimar",
    ],
  },
  {
    state_name: "Maharashtra",
    state_code: "MH",
    districts: [
      "Ahmednagar",
      "Akola",
      "Amravati",
      "Aurangabad",
      "Beed",
      "Bhandara",
      "Buldhana",
      "Chandrapur",
      "Dhule",
      "Gadchiroli",
      "Gondia",
      "Hingoli",
      "Jalgaon",
      "Jalna",
      "Kolhapur",
      "Latur",
      "Mumbai City",
      "Mumbai Suburban",
      "Nagpur",
      "Nanded",
      "Nandurbar",
      "Nashik",
      "Osmanabad",
      "Palghar",
      "Parbhani",
      "Pune",
      "Raigad",
      "Ratnagiri",
      "Sangli",
      "Satara",
      "Sindhudurg",
      "Solapur",
      "Thane",
      "Wardha",
      "Washim",
      "Yavatmal",
    ],
  },
  {
    state_name: "Manipur",
    state_code: "MN",
    districts: ["Bishnupur", "Chandel", "Imphal East", "Imphal West", "Jiribam", "Kakching", "Noney", "Pherzawl", "Senapati", "Tamenglong", "Thoubal", "Ukhrul"],
  },
  {
    state_name: "Meghalaya",
    state_code: "ML",
    districts: [
      "East Garo Hills",
      "East Jaintia Hills",
      "East Khasi Hills",
      "North Garo Hills",
      "Ri-Bhoi",
      "South Garo Hills",
      "South Jaintia Hills",
      "South West Garo Hills",
      "South West Khasi Hills",
      "West Garo Hills",
      "West Jaintia Hills",
      "West Khasi Hills",
    ],
  },
  {
    state_name: "Mizoram",
    state_code: "MZ",
    districts: ["Aizawl", "Champhai", "Khawzawl", "Kolasib", "Lunglei", "Lwthang", "Mamit", "Saiha", "Saitual", "Serchhip"],
  },
  {
    state_name: "Nagaland",
    state_code: "NL",
    districts: ["Dimapur", "Kiphire", "Kohima", "Longleng", "Mokokchung", "Mon", "Niuland", "Peren", "Phek", "Tuensang", "Wokha", "Zunheboto"],
  },
  {
    state_name: "Odisha",
    state_code: "OD",
    districts: [
      "Angul",
      "Balangir",
      "Balasore",
      "Bargarh",
      "Bhadrak",
      "Boudh",
      "Cuttack",
      "Deogarh",
      "Dhenkanal",
      "Gajapati",
      "Ganjam",
      "Jagatsinghpur",
      "Jajpur",
      "Jharsuguda",
      "Kalahandi",
      "Kandhamal",
      "Kendrapara",
      "Khurda",
      "Koraput",
      "Malkangiri",
      "Mayurbhanj",
      "Nabarangapur",
      "Nayagarh",
      "Nuapada",
      "Puri",
      "Rayagada",
      "Sambalpur",
      "Subarnapur",
      "Sundargarh",
    ],
  },
  {
    state_name: "Punjab",
    state_code: "PB",
    districts: [
      "Amritsar",
      "Barnala",
      "Bathinda",
      "Faridkot",
      "Fatehgarh Sahib",
      "Fazilka",
      "Ferozepur",
      "Gurdaspur",
      "Hoshiarpur",
      "Jalandhar",
      "Kapurthala",
      "Ludhiana",
      "Malerkotla",
      "Mansa",
      "Moga",
      "Muktsar",
      "Pathankot",
      "Patiala",
      "Rupnagar",
      "Sangrur",
      "SAS Nagar",
      "Tarn Taran",
    ],
  },
  {
    state_name: "Rajasthan",
    state_code: "RJ",
    districts: [
      "Ajmer",
      "Alwar",
      "Banswara",
      "Baran",
      "Barmer",
      "Bhilwara",
      "Bikaner",
      "Bundi",
      "Chittorgarh",
      "Churu",
      "Dausa",
      "Dungarpur",
      "Hanumangarh",
      "Jaipur",
      "Jaisalmer",
      "Jalore",
      "Jhalawar",
      "Jhunjhunu",
      "Jodhpur",
      "Karauli",
      "Kota",
      "Nagaur",
      "Pali",
      "Pratapgarh",
      "Rajsamand",
      "Sawai Madhopur",
      "Sikar",
      "Sirohi",
      "Tonk",
      "Udaipur",
    ],
  },
  {
    state_name: "Sikkim",
    state_code: "SK",
    districts: ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  },
  {
    state_name: "Tamil Nadu",
    state_code: "TN",
    districts: [
      "Ariyalur",
      "Chennai",
      "Coimbatore",
      "Cuddalore",
      "Dharmapuri",
      "Dindigul",
      "Erode",
      "Kallakurichi",
      "Kanchipuram",
      "Kanyakumari",
      "Karur",
      "Krishnagiri",
      "Madurai",
      "Mayiladuthurai",
      "Nagapattinam",
      "Namakkal",
      "Nilgiris",
      "Perambalur",
      "Pudukkottai",
      "Ramanathapuram",
      "Salem",
      "Sivaganga",
      "Tenkasi",
      "Thanjavur",
      "Theni",
      "Thiruvallur",
      "Thiruvarur",
      "Thoothukudi",
      "Tiruchirappalli",
      "Tirunelveli",
      "Tirupathur",
      "Tiruppur",
      "Vellore",
      "Viluppuram",
      "Virudhunagar",
    ],
  },
  {
    state_name: "Telangana",
    state_code: "TG",
    districts: [
      "Adilabad",
      "Bhadradri Kothagudem",
      "Hyderabad",
      "Jagtial",
      "Jangaon",
      "Jayashankar Bhupalpally",
      "Jogulamba Gadwal",
      "Kamareddy",
      "Karimnagar",
      "Khammam",
      "Komaram Bheem Asifabad",
      "Mahabubabad",
      "Mahbubnagar",
      "Mancherial",
      "Medak",
      "Medchal–Malkajgiri",
      "Mulugu",
      "Nagarkurnool",
      "Nalgonda",
      "Narayanpet",
      "Nirmal",
      "Nizamabad",
      "Peddapalli",
      "Rajanna Sircilla",
      "Ranga Reddy",
      "Sangareddy",
      "Siddipet",
      "Suryapet",
      "Vikarabad",
      "Wanaparthy",
      "Warangal",
      "Yadadri Bhuvanagiri",
    ],
  },
  {
    state_name: "Tripura",
    state_code: "TR",
    districts: ["Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala", "South Tripura", "Unakoti", "West Tripura"],
  },
  {
    state_name: "Uttar Pradesh",
    state_code: "UP",
    districts: [
      "Agra",
      "Aligarh",
      "Allahabad",
      "Ambedkar Nagar",
      "Amethi",
      "Amroha",
      "Auraiya",
      "Azamgarh",
      "Bagpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Barabanki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Faizabad",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kasganj",
      "Kaushambi",
      "Kushinagar",
      "Lakhimpur Kheri",
      "Lalitpur",
      "Lucknow",
      "Maharajganj",
      "Mahoba",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "Rae Bareli",
      "Rampur",
      "Saharanpur",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamli",
      "Shravasti",
      "Siddharthnagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
  },
  {
    state_name: "Uttarakhand",
    state_code: "UT",
    districts: ["Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag", "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi"],
  },
  {
    state_name: "West Bengal",
    state_code: "WB",
    districts: [
      "Alipurduar",
      "Bankura",
      "Birbhum",
      "Cooch Behar",
      "Dakshin Dinajpur",
      "Darjeeling",
      "Hooghly",
      "Howrah",
      "Jalpaiguri",
      "Jhargram",
      "Kalimpong",
      "Kolkata",
      "Malda",
      "Murshidabad",
      "Nadia",
      "North 24 Parganas",
      "Paschim Bardhaman",
      "Purba Bardhaman",
      "Purba Medinipur",
      "Puruliya",
      "South 24 Parganas",
      "Uttar Dinajpur",
    ],
  },

  // -------------------- Union Territories --------------------
  {
    state_name: "Andaman and Nicobar Islands",
    state_code: "AN",
    districts: ["Nicobar", "North and Middle Andaman", "South Andaman"],
  },
  {
    state_name: "Chandigarh",
    state_code: "CH",
    districts: ["Chandigarh"],
  },
  {
    state_name: "Dadra and Nagar Haveli and Daman and Diu",
    state_code: "DN",
    districts: ["Dadra and Nagar Haveli", "Daman", "Diu"],
  },
  {
    state_name: "Jammu and Kashmir",
    state_code: "JK",
    districts: ["Anantnag", "Bandipora", "Baramulla", "Budgam", "Doda", "Ganderbal", "Jammu", "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Leh and Ladakh", "Poonch", "Pulwama", "Rajouri", "Ramban", "Reasi", "Samba", "Shopian", "Srinagar", "Udhampur"],
  },
  {
    state_name: "Ladakh",
    state_code: "LA",
    districts: ["Kargil", "Leh"],
  },
  {
    state_name: "Lakshadweep",
    state_code: "LD",
    districts: ["Lakshadweep"],
  },
  {
    state_name: "Delhi",
    state_code: "DL",
    districts: ["Central Delhi", "East Delhi", "New Delhi", "North Delhi", "North East Delhi", "North West Delhi", "South Delhi", "South East Delhi", "South West Delhi", "West Delhi"],
  },
  {
    state_name: "Puducherry",
    state_code: "PY",
    districts: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
  },
];


export async function runSeeder(poolInstance) {
  const client = await poolInstance.connect();
  try {
    console.log("[Seeder Engine] Initiating Bruteforce Fallback Mapping Array...");
    
    // 1. Direct Column Exact Extraction
    const stateSample = await client.query("SELECT * FROM state_master LIMIT 0");
    const stateCols = stateSample.fields.map(f => f.name);
    const nameColOfState = stateCols.find(c => c === "state_name" || c === "name") || "name";
    const codeColOfState = stateCols.find(c => c === "state_code" || c === "code") || "code";

    const distSample = await client.query("SELECT * FROM district_master LIMIT 0");
    const distCols = distSample.fields.map(f => f.name);
    const nameColOfDist = distCols.find(c => c === "district_name" || c === "name") || "name";

    // 2. Sequential ID Normalization Setup
    const maxStateRes = await client.query('SELECT id FROM state_master');
    let nextStateId = 1;
    if (maxStateRes.rows.length > 0) {
      const ids = maxStateRes.rows.map(r => parseInt(r.id)).filter(id => !isNaN(id));
      if (ids.length > 0) nextStateId = Math.max(...ids) + 1;
    }

    const maxDistRes = await client.query('SELECT id FROM district_master');
    let nextDistId = 1;
    if (maxDistRes.rows.length > 0) {
      const ids = maxDistRes.rows.map(r => parseInt(r.id)).filter(id => !isNaN(id));
      if (ids.length > 0) nextDistId = Math.max(...ids) + 1;
    }

    // 3. Execution Main Seed Block
    for (const item of INDIA_DATA) {
      let stateId;
      
      const existingState = await client.query(
        `SELECT id FROM state_master WHERE "${codeColOfState}" = $1`,
        [item.state_code.toUpperCase()]
      );

      if (existingState.rows.length > 0) {
        stateId = existingState.rows[0].id;
        await client.query(
          `UPDATE state_master SET "${nameColOfState}" = $1 WHERE id = $2`,
          [item.state_name, stateId]
        );
      } else {
        stateId = String(nextStateId++);
        await client.query(
          `INSERT INTO state_master (id, "${nameColOfState}", "${codeColOfState}") VALUES ($1, $2, $3)`,
          [stateId, item.state_name, item.state_code.toUpperCase()]
        );
        console.log(`[Seeder] Registered State: ${item.state_name} (ID: ${stateId})`);
      }

      // 4. District Loop with Bruteforce Fallback Array Matrix
      for (const distName of item.districts) {
        let inserted = false;
        
        // Target strategies array list
        const strategies = [
          { column: "state_id", value: stateId },
          { column: "state_code", value: item.state_code.toUpperCase() },
          { column: "state", value: stateId },
          { column: "stateId", value: stateId }
        ];

        for (const strat of strategies) {
          if (inserted) break;
          
          try {
            // Check existence first
            const existingDist = await client.query(
              `SELECT id FROM district_master WHERE "${nameColOfDist}" = $1 AND "${strat.column}" = $2`,
              [distName, strat.value]
            );

            if (existingDist.rows.length > 0) {
              inserted = true;
              break;
            }

            // Attempt explicit write command execution
            const currentDistId = String(nextDistId++);
            const distQuery = `
              INSERT INTO district_master (id, "${nameColOfDist}", "${strat.column}") 
              VALUES ($1, $2, $3)
            `;
            await client.query(distQuery, [currentDistId, distName, strat.value]);
            inserted = true;
          } catch (e) {
            // Error code 42703 matches missing column, we let it loop to the next strategy matrix smoothly
            if (e.code !== "42703") {
              throw e; // Reroute fatal errors like key violations upwards
            }
          }
        }
      }
    }

    console.log("[Success Master Check] All Indian states and districts populated successfully via brutal execution pipeline!");
  } catch (error) {
    console.error("[Seeder Error] Critical pipeline breach during injection sequence:", error);
  } finally {
    client.release();
  }
}